### ISSUE TITLE
pod 不能install 问题

### ISSUE THREAD

**Issue by lisheng1219** [Seanwong933/WeChat#1]
加上target + end 就可以解决了，并不是你说的环境问题
![0fe5bd31-e024-48da-8640-1e6f0b407c28](https://user-images.githubusercontent.com/8164223/37396415-cd428fdc-27b3-11e8-92f9-9f2139db825b.png)

**Comment by siegrainwong** [comment]
不是很清楚你想表达的意思。
指定`target`是`cocoapods`1.0的新语法，我那时候并没有使用。
